fixed bug where aria2 wouldn't start

diff --git a/provision/daemons/aria2d b/provision/daemons/aria2d
--- a/provision/daemons/aria2d
+++ b/provision/daemons/aria2d
@@ -1,5 +1,5 @@
 #! /bin/sh
-# /etc/init.d/aria2
+# /etc/init.d/aria2d
  
 ### BEGIN INIT INFO
 # Provides: aria2cRPC
@@ -21,21 +21,37 @@ start)
 	RETVAL=$?
 	;;
 stop)
-	log_daemon_msg "Stopping aria2c daemon"
-	start-stop-daemon --stop --oknodo --chuid "root" --retry 3 --exec "$(which aria2c)"
-	RETVAL=$?
-	;;
-force-stop)
-	log_daemon_msg "Forcibly stopping aria2c daemon"
-	start-stop-daemon --stop --oknodo --chuid "root" --signal 9 --exec "$(which aria2c)"
-	RETVAL=$?
+	forced=false
+	arg_counter=2
+	while [ $arg_counter -le $# ]
+	do
+		arg=${!$arg_counter}
+		if [ "$arg" == "-f" ] || [ "$arg" == "--force" ]
+		then
+			forced=true
+		else
+			>&2 echo "invalid parameter $arg"
+			exit 1
+		fi
+		arg_counter=$(($arg_counter+1))
+	done
+	if $forced
+	then
+		log_daemon_msg "Forcibly stopping aria2c daemon"
+		start-stop-daemon --stop --oknodo --chuid "root" --signal 9 --exec "$(which aria2c)"
+		RETVAL=$?
+	else
+		log_daemon_msg "Stopping aria2c daemon"
+		start-stop-daemon --stop --oknodo --chuid "root" --retry 3 --exec "$(which aria2c)"
+		RETVAL=$?
+	fi
 	;;
 restart)
 	stop
 	start
 	;;
 *)
-	echo $"Usage: $0 {start|stop|force-stop|restart|status}"
+	echo "Usage: $0 {start|stop|restart|status}"
 	RETVAL=1
 esac
 exit $RETVAL
